{
 "title": "Home",
 "description": "Overview of all endpoints",
 "time": { "from": "", "to": "" },
 "templating": {
  "list": [
   {
    "name": "runid",
    "label": "Run",
    "query": "SELECT id FROM runs ORDER BY id DESC"
   },
   {
    "name": "min_time",
    "label": "Min Time",
    "query": "SELECT CAST(MIN(strftime('%s', timestamp)) AS INTEGER) * 1000 FROM coverage WHERE runid = $runid"
   },
   {
    "name": "max_time",
    "label": "Max Time",
    "query": "SELECT CAST(MAX(strftime('%s', timestamp)) AS INTEGER) * 1000 FROM coverage WHERE runid = $runid"
   },
   {
    "name": "endpoint",
    "label": "Endpoint",
    "query": "SELECT DISTINCT path FROM requests WHERE runid = $runid ORDER BY path ASC"
   }
  ]
 },
 "panels": [
  {
   "title": "Status codes",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "queryText": "SELECT\r\n  -- 1xx Informational\r\n  SUM(CASE WHEN status = '100' THEN 1 ELSE 0 END) AS \"100\",\r\n  SUM(CASE WHEN status = '101' THEN 1 ELSE 0 END) AS \"101\",\r\n  SUM(CASE WHEN status = '102' THEN 1 ELSE 0 END) AS \"102\",\r\n\r\n  -- 2xx Success\r\n  SUM(CASE WHEN status = '200' THEN 1 ELSE 0 END) AS \"200\",\r\n  SUM(CASE WHEN status = '201' THEN 1 ELSE 0 END) AS \"201\",\r\n  SUM(CASE WHEN status = '202' THEN 1 ELSE 0 END) AS \"202\",\r\n  SUM(CASE WHEN status = '203' THEN 1 ELSE 0 END) AS \"203\",\r\n  SUM(CASE WHEN status = '204' THEN 1 ELSE 0 END) AS \"204\",\r\n  SUM(CASE WHEN status = '205' THEN 1 ELSE 0 END) AS \"205\",\r\n  SUM(CASE WHEN status = '206' THEN 1 ELSE 0 END) AS \"206\",\r\n\r\n  -- 3xx Redirection\r\n  SUM(CASE WHEN status = '300' THEN 1 ELSE 0 END) AS \"300\",\r\n  SUM(CASE WHEN status = '301' THEN 1 ELSE 0 END) AS \"301\",\r\n  SUM(CASE WHEN status = '302' THEN 1 ELSE 0 END) AS \"302\",\r\n  SUM(CASE WHEN status = '303' THEN 1 ELSE 0 END) AS \"303\",\r\n  SUM(CASE WHEN status = '304' THEN 1 ELSE 0 END) AS \"304\",\r\n  SUM(CASE WHEN status = '305' THEN 1 ELSE 0 END) AS \"305\",\r\n  SUM(CASE WHEN status = '307' THEN 1 ELSE 0 END) AS \"307\",\r\n  SUM(CASE WHEN status = '308' THEN 1 ELSE 0 END) AS \"308\",\r\n\r\n  -- 4xx Client Errors\r\n  SUM(CASE WHEN status = '400' THEN 1 ELSE 0 END) AS \"400\",\r\n  SUM(CASE WHEN status = '401' THEN 1 ELSE 0 END) AS \"401\",\r\n  SUM(CASE WHEN status = '402' THEN 1 ELSE 0 END) AS \"402\",\r\n  SUM(CASE WHEN status = '403' THEN 1 ELSE 0 END) AS \"403\",\r\n  SUM(CASE WHEN status = '404' THEN 1 ELSE 0 END) AS \"404\",\r\n  SUM(CASE WHEN status = '405' THEN 1 ELSE 0 END) AS \"405\",\r\n  SUM(CASE WHEN status = '406' THEN 1 ELSE 0 END) AS \"406\",\r\n  SUM(CASE WHEN status = '407' THEN 1 ELSE 0 END) AS \"407\",\r\n  SUM(CASE WHEN status = '408' THEN 1 ELSE 0 END) AS \"408\",\r\n  SUM(CASE WHEN status = '409' THEN 1 ELSE 0 END) AS \"409\",\r\n  SUM(CASE WHEN status = '410' THEN 1 ELSE 0 END) AS \"410\",\r\n  SUM(CASE WHEN status = '411' THEN 1 ELSE 0 END) AS \"411\",\r\n  SUM(CASE WHEN status = '412' THEN 1 ELSE 0 END) AS \"412\",\r\n  SUM(CASE WHEN status = '413' THEN 1 ELSE 0 END) AS \"413\",\r\n  SUM(CASE WHEN status = '414' THEN 1 ELSE 0 END) AS \"414\",\r\n  SUM(CASE WHEN status = '415' THEN 1 ELSE 0 END) AS \"415\",\r\n  SUM(CASE WHEN status = '416' THEN 1 ELSE 0 END) AS \"416\",\r\n  SUM(CASE WHEN status = '417' THEN 1 ELSE 0 END) AS \"417\",\r\n  SUM(CASE WHEN status = '418' THEN 1 ELSE 0 END) AS \"418\",\r\n  SUM(CASE WHEN status = '422' THEN 1 ELSE 0 END) AS \"422\",\r\n  SUM(CASE WHEN status = '426' THEN 1 ELSE 0 END) AS \"426\",\r\n  SUM(CASE WHEN status = '429' THEN 1 ELSE 0 END) AS \"429\",\r\n  SUM(CASE WHEN status = '431' THEN 1 ELSE 0 END) AS \"431\",\r\n\r\n  -- 5xx Server Errors\r\n  SUM(CASE WHEN status = '500' THEN 1 ELSE 0 END) AS \"500\",\r\n  SUM(CASE WHEN status = '501' THEN 1 ELSE 0 END) AS \"501\",\r\n  SUM(CASE WHEN status = '502' THEN 1 ELSE 0 END) AS \"502\",\r\n  SUM(CASE WHEN status = '503' THEN 1 ELSE 0 END) AS \"503\",\r\n  SUM(CASE WHEN status = '504' THEN 1 ELSE 0 END) AS \"504\",\r\n  SUM(CASE WHEN status = '505' THEN 1 ELSE 0 END) AS \"505\",\r\n  SUM(CASE WHEN status = '507' THEN 1 ELSE 0 END) AS \"507\",\r\n  SUM(CASE WHEN status = '508' THEN 1 ELSE 0 END) AS \"508\",\r\n  SUM(CASE WHEN status = '510' THEN 1 ELSE 0 END) AS \"510\",\r\n  SUM(CASE WHEN status = '511' THEN 1 ELSE 0 END) AS \"511\"\r\n\r\nFROM responses\r\nLEFT JOIN requests ON responses.reqid = requests.id\r\nWHERE \r\n    runid = $runid AND\r\n    path IN (${endpoint:sqlstring})\r\n",
     "rawQueryText": "SELECT\r\n  -- 1xx Informational\r\n  SUM(CASE WHEN status = '100' THEN 1 ELSE 0 END) AS \"100\",\r\n  SUM(CASE WHEN status = '101' THEN 1 ELSE 0 END) AS \"101\",\r\n  SUM(CASE WHEN status = '102' THEN 1 ELSE 0 END) AS \"102\",\r\n\r\n  -- 2xx Success\r\n  SUM(CASE WHEN status = '200' THEN 1 ELSE 0 END) AS \"200\",\r\n  SUM(CASE WHEN status = '201' THEN 1 ELSE 0 END) AS \"201\",\r\n  SUM(CASE WHEN status = '202' THEN 1 ELSE 0 END) AS \"202\",\r\n  SUM(CASE WHEN status = '203' THEN 1 ELSE 0 END) AS \"203\",\r\n  SUM(CASE WHEN status = '204' THEN 1 ELSE 0 END) AS \"204\",\r\n  SUM(CASE WHEN status = '205' THEN 1 ELSE 0 END) AS \"205\",\r\n  SUM(CASE WHEN status = '206' THEN 1 ELSE 0 END) AS \"206\",\r\n\r\n  -- 3xx Redirection\r\n  SUM(CASE WHEN status = '300' THEN 1 ELSE 0 END) AS \"300\",\r\n  SUM(CASE WHEN status = '301' THEN 1 ELSE 0 END) AS \"301\",\r\n  SUM(CASE WHEN status = '302' THEN 1 ELSE 0 END) AS \"302\",\r\n  SUM(CASE WHEN status = '303' THEN 1 ELSE 0 END) AS \"303\",\r\n  SUM(CASE WHEN status = '304' THEN 1 ELSE 0 END) AS \"304\",\r\n  SUM(CASE WHEN status = '305' THEN 1 ELSE 0 END) AS \"305\",\r\n  SUM(CASE WHEN status = '307' THEN 1 ELSE 0 END) AS \"307\",\r\n  SUM(CASE WHEN status = '308' THEN 1 ELSE 0 END) AS \"308\",\r\n\r\n  -- 4xx Client Errors\r\n  SUM(CASE WHEN status = '400' THEN 1 ELSE 0 END) AS \"400\",\r\n  SUM(CASE WHEN status = '401' THEN 1 ELSE 0 END) AS \"401\",\r\n  SUM(CASE WHEN status = '402' THEN 1 ELSE 0 END) AS \"402\",\r\n  SUM(CASE WHEN status = '403' THEN 1 ELSE 0 END) AS \"403\",\r\n  SUM(CASE WHEN status = '404' THEN 1 ELSE 0 END) AS \"404\",\r\n  SUM(CASE WHEN status = '405' THEN 1 ELSE 0 END) AS \"405\",\r\n  SUM(CASE WHEN status = '406' THEN 1 ELSE 0 END) AS \"406\",\r\n  SUM(CASE WHEN status = '407' THEN 1 ELSE 0 END) AS \"407\",\r\n  SUM(CASE WHEN status = '408' THEN 1 ELSE 0 END) AS \"408\",\r\n  SUM(CASE WHEN status = '409' THEN 1 ELSE 0 END) AS \"409\",\r\n  SUM(CASE WHEN status = '410' THEN 1 ELSE 0 END) AS \"410\",\r\n  SUM(CASE WHEN status = '411' THEN 1 ELSE 0 END) AS \"411\",\r\n  SUM(CASE WHEN status = '412' THEN 1 ELSE 0 END) AS \"412\",\r\n  SUM(CASE WHEN status = '413' THEN 1 ELSE 0 END) AS \"413\",\r\n  SUM(CASE WHEN status = '414' THEN 1 ELSE 0 END) AS \"414\",\r\n  SUM(CASE WHEN status = '415' THEN 1 ELSE 0 END) AS \"415\",\r\n  SUM(CASE WHEN status = '416' THEN 1 ELSE 0 END) AS \"416\",\r\n  SUM(CASE WHEN status = '417' THEN 1 ELSE 0 END) AS \"417\",\r\n  SUM(CASE WHEN status = '418' THEN 1 ELSE 0 END) AS \"418\",\r\n  SUM(CASE WHEN status = '422' THEN 1 ELSE 0 END) AS \"422\",\r\n  SUM(CASE WHEN status = '426' THEN 1 ELSE 0 END) AS \"426\",\r\n  SUM(CASE WHEN status = '429' THEN 1 ELSE 0 END) AS \"429\",\r\n  SUM(CASE WHEN status = '431' THEN 1 ELSE 0 END) AS \"431\",\r\n\r\n  -- 5xx Server Errors\r\n  SUM(CASE WHEN status = '500' THEN 1 ELSE 0 END) AS \"500\",\r\n  SUM(CASE WHEN status = '501' THEN 1 ELSE 0 END) AS \"501\",\r\n  SUM(CASE WHEN status = '502' THEN 1 ELSE 0 END) AS \"502\",\r\n  SUM(CASE WHEN status = '503' THEN 1 ELSE 0 END) AS \"503\",\r\n  SUM(CASE WHEN status = '504' THEN 1 ELSE 0 END) AS \"504\",\r\n  SUM(CASE WHEN status = '505' THEN 1 ELSE 0 END) AS \"505\",\r\n  SUM(CASE WHEN status = '507' THEN 1 ELSE 0 END) AS \"507\",\r\n  SUM(CASE WHEN status = '508' THEN 1 ELSE 0 END) AS \"508\",\r\n  SUM(CASE WHEN status = '510' THEN 1 ELSE 0 END) AS \"510\",\r\n  SUM(CASE WHEN status = '511' THEN 1 ELSE 0 END) AS \"511\"\r\n\r\nFROM responses\r\nLEFT JOIN requests ON responses.reqid = requests.id\r\nWHERE \r\n    runid = $runid AND\r\n    path IN (${endpoint:sqlstring})\r\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Number of requests per path",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 20, "x": 4, "y": 0 },
   "targets": [
    {
     "queryText": "SELECT \n    path as metric,\n    NULLIF(count(1) filter(where status BETWEEN 400 AND 499), 0) as \"4xx\",\n    NULLIF(count(1) filter(where status BETWEEN 500 AND 599), 0) as \"5xx\",\n    NULLIF(count(1) filter(where status BETWEEN 200 AND 299), 0) as \"2xx\",\n    NULLIF(count(1) filter(where status NOT BETWEEN 400 AND 599 AND status NOT BETWEEN 200 AND 299), 0) as other\nFROM \n    requests LEFT JOIN responses ON responses.reqid = requests.id\nWHERE \n    runid = $runid AND\n    path IN (${endpoint:sqlstring})\nGROUP BY path",
     "rawQueryText": "SELECT \n    path as metric,\n    NULLIF(count(1) filter(where status BETWEEN 400 AND 499), 0) as \"4xx\",\n    NULLIF(count(1) filter(where status BETWEEN 500 AND 599), 0) as \"5xx\",\n    NULLIF(count(1) filter(where status BETWEEN 200 AND 299), 0) as \"2xx\",\n    NULLIF(count(1) filter(where status NOT BETWEEN 400 AND 599 AND status NOT BETWEEN 200 AND 299), 0) as other\nFROM \n    requests LEFT JOIN responses ON responses.reqid = requests.id\nWHERE \n    runid = $runid AND\n    path IN (${endpoint:sqlstring})\nGROUP BY path",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Coverage",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "queryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%SZ', timestamp) as time,\n  100.0 * endpoint_coverage / endpoint_coverage_total AS \"Endpoint Coverage (%)\",\n  100.0 * line_coverage / line_coverage_total AS \"Line Coverage (%)\"\nFROM\n  coverage\nWHERE\n  runid = \"$runid\"\n",
     "rawQueryText": "SELECT\n  strftime('%Y-%m-%dT%H:%M:%SZ', timestamp) as time,\n  100.0 * endpoint_coverage / endpoint_coverage_total AS \"Endpoint Coverage (%)\",\n  100.0 * line_coverage / line_coverage_total AS \"Line Coverage (%)\"\nFROM\n  coverage\nWHERE\n  runid = \"$runid\"\n",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "targets": [
    {
     "queryText": "SELECT strftime('%Y-%m-%dT%H:%M:%SZ', timestamp) as time, seq_per_sec as \"seq/sec\", req_per_sec as \"req/sec\" FROM stats WHERE runid = \"$runid\" ORDER BY timestamp",
     "rawQueryText": "SELECT strftime('%Y-%m-%dT%H:%M:%SZ', timestamp) as time, seq_per_sec as \"seq/sec\", req_per_sec as \"req/sec\" FROM stats WHERE runid = \"$runid\" ORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "Corpus, Objectives & Requests Completed",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "targets": [
    {
     "queryText": "SELECT strftime('%Y-%m-%dT%H:%M:%SZ', timestamp) as time, corpus_size as \"Corpus size\", objectives as \"Objectives\", requests_completed_total as \"Requests completed\" FROM stats WHERE runid = \"$runid\" ORDER BY timestamp",
     "rawQueryText": "SELECT strftime('%Y-%m-%dT%H:%M:%SZ', timestamp) as time, corpus_size as \"Corpus size\", objectives as \"Objectives\", requests_completed_total as \"Requests completed\" FROM stats WHERE runid = \"$runid\" ORDER BY timestamp",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  },
  {
   "title": "All Status Codes",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "queryText": "SELECT \n    path as path,\n    CAST(status AS TEXT) as status,\n    count(1) as count\nFROM \n    requests LEFT JOIN responses ON responses.reqid = requests.id\nWHERE \n    runid = $runid AND\n    path IN (${endpoint:sqlstring})\nGROUP BY path, status",
     "rawQueryText": "SELECT \n    path as path,\n    CAST(status AS TEXT) as status,\n    count(1) as count\nFROM \n    requests LEFT JOIN responses ON responses.reqid = requests.id\nWHERE \n    runid = $runid AND\n    path IN (${endpoint:sqlstring})\nGROUP BY path, status",
     "timeColumns": [
      "time",
      "ts"
     ]
    }
   ]
  }
 ]
}