services:
  grafana-dashboard:
    image: grafana/grafana-enterprise
    ports:
      - "3000:3000"
    environment:
      - GF_INSTALL_PLUGINS=frser-sqlite-datasource
    volumes:
      - type: bind
        source: ../reports/grafana/report.db
        target: /var/lib/grafana/datasources/report.db
      - type: bind
        source: provisioning/dashboards
        target: /var/lib/grafana/dashboards
      - type: bind
        source: ./grafana.ini
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ./provisioning
        target: /etc/grafana/provisioning
