services:
  grafana-dashboard:
    build:
      context: .
      dockerfile: docker/grafana/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - type: bind
        source: ../reports/grafana/report.db
        target: /home/grafana/report.db
      - type: bind
        source: provisioning/dashboards
        target: /var/lib/grafana/dashboards
      - type: bind
        source: ./grafana.ini
        target: /etc/grafana/grafana.ini
      - type: bind
        source: ./provisioning
        target: /etc/grafana/provisioning
